# Generated by Django 4.0.3 on 2022-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyslotbooking',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
