# Generated by Django 4.0.3 on 2022-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_dailyslotbooking_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyslotbooking',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
