# Generated by Django 4.0.3 on 2022-05-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_prescription_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
