# Generated by Django 4.0.3 on 2022-05-07 19:42

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=patient.models.get_expiry_time),
        ),
    ]
