# Generated by Django 4.0.3 on 2022-05-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
    ]
