# Generated by Django 4.0.3 on 2022-04-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='half_time',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default=('Morning', 'Morning'), max_length=50, null=True),
        ),
    ]
