# Generated by Django 4.0.3 on 2022-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_timeslot_half_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='half_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
