# Generated by Django 4.0.3 on 2022-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_timeslot_half_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslot',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
